name: fitness
description: Flutter plugin for reading step count data. Wraps HealthKit on iOS and GoogleFit on Android.
version: 1.0.1
homepage: https://github.com/dev-juyoung/Fitness

environment:
  sdk:
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.juyoung.fitness
        pluginClass: FitnessPlugin
      ios:
        pluginClass: FitnessPlugin
